name: final_project_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - wandb
    - torch==1.12.1
    - matplotlib
    - pandas
    - transformers
    - scipy
    - scikit-learn
    - seaborn==0.13.2
    - shap==0.44.1
    - lime==0.2.0.1
    - graphviz==0.20.3